version: 0.2
env:
  parameter-store:
    MONGO_EP: mongo_ep
    
phases:
  install:
      -nodejs: 12
      
  build:
    commands:
      - npm install
      - sed -i "s|mongo_ep|${MONGO_EP}" app.js
      
      
artifacts:
  files:
    - '**/*'
